server:
  port: 9015
spring:
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
#        namespace: 309a1a24-556b-42f6-a24a-ba6434062b54
  application:
    name: nacos-provide
#    不写服务名就不会注册